# Generated by Django 5.0.14 on 2025-10-18 21:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitAxeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bitaxe_devices',
            },
        ),
        migrations.RunSQL(
            'ALTER TABLE bitaxe_devices ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;',
            ),
        migrations.CreateModel(
            name='BitAxeHardwareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('power_watts', models.FloatField(help_text='Power consumption in Watts')),
                ('efficiency_j_per_th', models.FloatField(blank=True, help_text='Joules per TeraHash', null=True)),
                ('temperature_c', models.FloatField(help_text='Temperature in Celsius')),
                ('fan_speed_rpm', models.IntegerField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('frequency_mhz', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_logs', to='api.bitaxedevice')),
            ],
            options={
                'db_table': 'bitaxe_hardware_logs',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='bitaxe_hard_device__f67a33_idx')],
            },
        ),
        migrations.RunSQL(
            'ALTER TABLE bitaxe_hardware_logs ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;',
            ),
        migrations.CreateModel(
            name='BitAxeMiningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('hashrate_ghs', models.FloatField(help_text='Hash rate in GH/s')),
                ('shares_accepted', models.IntegerField()),
                ('shares_rejected', models.IntegerField()),
                ('blocks_found', models.IntegerField(default=0)),
                ('uptime_seconds', models.IntegerField()),
                ('best_difficulty', models.BigIntegerField(blank=True, null=True)),
                ('pool_url', models.CharField(blank=True, max_length=255, null=True)),
                ('pool_user', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_stats', to='api.bitaxedevice')),
            ],
            options={
                'db_table': 'bitaxe_mining_stats',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='bitaxe_mini_device__cdbd9e_idx')],
            },
        ),
        migrations.RunSQL(
            'ALTER TABLE bitaxe_mining_stats ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;',
            )
    ]
