# Generated by Django 5.0.14 on 2025-10-19 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitAxePoolStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_address', models.CharField(db_index=True, help_text='Bitcoin address or pool username', max_length=255)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('hashrate_1m', models.CharField(help_text='1 minute hashrate', max_length=20)),
                ('hashrate_5m', models.CharField(help_text='5 minute hashrate', max_length=20)),
                ('hashrate_1hr', models.CharField(help_text='1 hour hashrate', max_length=20)),
                ('hashrate_1d', models.CharField(help_text='1 day hashrate', max_length=20)),
                ('hashrate_7d', models.CharField(help_text='7 day hashrate', max_length=20)),
                ('lastshare', models.BigIntegerField(help_text='Unix timestamp of last share')),
                ('workers', models.IntegerField(help_text='Number of active workers')),
                ('shares', models.BigIntegerField(help_text='Total shares submitted')),
                ('bestshare', models.FloatField(help_text='Best share difficulty')),
                ('bestever', models.BigIntegerField(help_text='Best ever difficulty')),
                ('authorised', models.BigIntegerField(help_text='Unix timestamp of authorization')),
                ('hashrate_1m_ghs', models.FloatField(blank=True, help_text='1m hashrate converted to GH/s', null=True)),
                ('hashrate_1d_ghs', models.FloatField(blank=True, help_text='1d hashrate converted to GH/s', null=True)),
            ],
            options={
                'verbose_name': 'Bitaxe Pool Statistics',
                'verbose_name_plural': 'Bitaxe Pool Statistics',
                'db_table': 'bitaxe_pool_stats',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['pool_address', '-recorded_at'], name='bitaxe_pool_pool_ad_5d49de_idx'), models.Index(fields=['-recorded_at'], name='bitaxe_pool_recorde_13331a_idx')],
            },
        ),
    ]
