# Generated by Django 5.0.14 on 2025-10-19 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bitaxepoolstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitAxeSystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('asic_model', models.CharField(blank=True, max_length=50, null=True)),
                ('board_version', models.CharField(blank=True, max_length=50, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('axe_os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('idf_version', models.CharField(blank=True, max_length=50, null=True)),
                ('running_partition', models.CharField(blank=True, max_length=50, null=True)),
                ('ssid', models.CharField(blank=True, max_length=100, null=True)),
                ('wifi_status', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi_rssi', models.IntegerField(blank=True, help_text='WiFi signal strength', null=True)),
                ('core_voltage', models.IntegerField(blank=True, null=True)),
                ('core_voltage_actual', models.IntegerField(blank=True, null=True)),
                ('expected_hashrate', models.FloatField(blank=True, null=True)),
                ('pool_difficulty', models.IntegerField(blank=True, null=True)),
                ('small_core_count', models.IntegerField(blank=True, null=True)),
                ('vr_temp', models.IntegerField(blank=True, help_text='Voltage regulator temperature', null=True)),
                ('temp_target', models.IntegerField(blank=True, null=True)),
                ('overheat_mode', models.IntegerField(default=0)),
                ('auto_fan_speed', models.BooleanField(default=True)),
                ('fan_speed_percent', models.IntegerField(blank=True, null=True)),
                ('min_fan_speed', models.IntegerField(blank=True, null=True)),
                ('max_power', models.FloatField(blank=True, null=True)),
                ('nominal_voltage', models.FloatField(blank=True, null=True)),
                ('overclock_enabled', models.BooleanField(default=False)),
                ('display_type', models.CharField(blank=True, max_length=50, null=True)),
                ('display_rotation', models.IntegerField(default=0)),
                ('invert_screen', models.BooleanField(default=False)),
                ('display_timeout', models.IntegerField(default=-1)),
                ('stratum_url', models.CharField(blank=True, max_length=255, null=True)),
                ('stratum_port', models.IntegerField(blank=True, null=True)),
                ('stratum_user', models.CharField(blank=True, max_length=255, null=True)),
                ('fallback_stratum_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fallback_stratum_port', models.IntegerField(blank=True, null=True)),
                ('is_using_fallback', models.BooleanField(default=False)),
                ('free_heap', models.BigIntegerField(blank=True, null=True)),
                ('is_psram_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_info', to='api.bitaxedevice')),
            ],
            options={
                'db_table': 'bitaxe_system_info',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='bitaxe_syst_device__e1c402_idx')],
            },
        ),
        migrations.RunSQL(
            'ALTER TABLE bitaxe_system_info ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;',
            )
    ]
