# Generated by Django 4.2.25 on 2025-10-25 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_device_status_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvalonDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'avalon_devices',
            },
        ),
        migrations.RunSQL(
            'ALTER TABLE avalon_devices ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;',
            ),
        migrations.CreateModel(
            name='AvalonSystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('hardware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=18, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('wifi_ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('wifi_signal_strength', models.IntegerField(blank=True, null=True)),
                ('primary_pool_url', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_pool_user', models.CharField(blank=True, max_length=255, null=True)),
                ('backup_pool_url', models.CharField(blank=True, max_length=255, null=True)),
                ('backup_pool_user', models.CharField(blank=True, max_length=255, null=True)),
                ('active_pool', models.CharField(blank=True, max_length=255, null=True)),
                ('system_uptime_seconds', models.IntegerField(default=0)),
                ('memory_usage_percent', models.FloatField(default=0.0)),
                ('storage_usage_percent', models.FloatField(default=0.0)),
                ('target_frequency', models.FloatField(default=0.0)),
                ('target_voltage', models.FloatField(default=0.0)),
                ('auto_tune_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_info', to='api.avalondevice')),
            ],
            options={
                'db_table': 'avalon_system_info',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='avalon_syst_device__0b3a11_idx')],
            },
        ),
        migrations.RunSQL(
            'ALTER TABLE avalon_system_info ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;',
            ),
        migrations.CreateModel(
            name='AvalonMiningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('hashrate_ghs', models.FloatField(help_text='Hashrate in GH/s')),
                ('shares_accepted', models.IntegerField(default=0)),
                ('shares_rejected', models.IntegerField(default=0)),
                ('blocks_found', models.IntegerField(default=0)),
                ('uptime_seconds', models.IntegerField(default=0)),
                ('difficulty', models.FloatField(default=0.0)),
                ('pool_url', models.CharField(blank=True, max_length=255, null=True)),
                ('pool_user', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_stats', to='api.avalondevice')),
            ],
            options={
                'db_table': 'avalon_mining_stats',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='avalon_mini_device__d35424_idx')],
            },
        ),
        migrations.RunSQL(
            'ALTER TABLE avalon_mining_stats ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;',
            ),
        migrations.CreateModel(
            name='AvalonHardwareLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('power_watts', models.FloatField(default=0.0)),
                ('efficiency_j_per_th', models.FloatField(default=0.0, help_text='Power efficiency in J/TH')),
                ('temperature_c', models.FloatField(default=0.0)),
                ('fan_speed_rpm', models.IntegerField(default=0)),
                ('voltage', models.FloatField(default=0.0)),
                ('frequency_mhz', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_logs', to='api.avalondevice')),
            ],
            options={
                'db_table': 'avalon_hardware_logs',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='avalon_hard_device__30e8e4_idx')],
            },
        ),
        migrations.RunSQL(
            'ALTER TABLE avalon_hardware_logs ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;',
            )
    ]
