# Generated by Django 5.x for AlertEvent (control audit + activity journal)

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_parasite_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(
                    choices=[('info', 'Info'), ('warn', 'Warning'), ('critical', 'Critical')],
                    db_index=True,
                    default='info',
                    max_length=16,
                )),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='alert_events',
                    to='api.device',
                )),
            ],
            options={
                'db_table': 'alert_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['-created_at'], name='alert_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['event_type', '-created_at'], name='alert_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['device', '-created_at'], name='alert_event_device_idx'),
        ),
    ]
